travis:
  secure:
    BINSTAR_TOKEN: YPyIXp2QwwKR3rp4knf3GDGVlsmgpnKAhYpfUpBWGaJEVn7I8iEmEkBRvOogdNFpQCSdxbCnYQkNinlQId6TaW9NZ2zZEQ9NB7IdTAwclCK+YY/E+9SDb1SN5tC7VFK4izA+MEtKsPduWDE7v2nryxk8KRIugD1yyOozKhjSylTDDDAmtd48KuPhGp+2gPaX9S7daH0B/gTrtbH8XML2y/I1PVAhriQC+hN5EzNM1+MXZ2hKM7dyiYJTnc1+eNHaB8L9M1wb17bJmdW9pqeHyLNhAxl0aqBFDnUGXMI8jVHm4zqnCF7WEc9AXd2j//NT2ekMRAQbRnomvNRC6vhAwdp9YmJgrmVQJOBdjdxo62hqFndeO/BoYxWuQTObWSvaZvmA/Ht9ul7gvu9WuoIC9NXxqwbi0YNbUlBqf7TfMwhQRSD4EljlwPS7DqcxRMg2ZvGeTTHibg4ROixklKBSg3z+CQD9tkbsIn5JBVy6m/tixk0rfCqKLx4PdulIGk3nFJDM/XVcGKyQPMxs2wJCcOsgMVuu/imvAlqdGTfXO3CxJbYh/JBVPfiNWzO9ioe7kNWu2MDPizuIg/BC2XG5igI9jTTEI19XlfMLfMjGZHKuVwEeZdk2Kq6aD/K8GI8aw/w3wwVkSh1pZzWbqVc8hXid04lhsR+zOESiLovvxjw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
